// <auto-generated />
namespace ArtGallery_ECommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class checkintoseeifvirtualiscreatingextradbproducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checkintoseeifvirtualiscreatingextradbproducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201808070001451_checkin to see if virtual is creating extra db products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
