// <auto-generated />
namespace ArtGallery_ECommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removingfkpointerinordermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removingfkpointerinordermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201808062345311_removing fk pointer in order model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
